FROM python:3.12.1
ENV EMSDK=/opt/emsdk EMSDK_NODE=/opt/emsdk/node/18.20.3_64bit/bin/node \
    PATH=/opt/emsdk:/opt/emsdk/upstream/emscripten:/opt/emsdk/node/18.20.3_64bit/bin:$PATH
RUN git clone https://github.com/emscripten-core/emsdk.git $EMSDK &&\
    emsdk install 3.1.58 && emsdk activate 3.1.58 &&\
    pip install pyodide-build==0.26.1 &&\
    python -c "from pyodide_build.build_env import init_environment; init_environment()"

COPY zengl-stubs /zengl/zengl-stubs
COPY setup.py pyproject.toml MANIFEST.in README.md zengl.c _zengl.py zengl.js /zengl/
RUN pyodide build /zengl -o /web/

COPY examples/pyodide/public /web
CMD python -m http.server -d web
